/* File generated by ExtractBody by Sandro Tolaini */

#define BODY_inno_Width 291
#define BODY_inno_Height 32
#define BODY_inno_Depth 2
#define BODY_inno_Masking 2
#define BODY_inno_Transparent 0
#define BODY_inno_Compression 1

extern unsigned long BODY_inno_Colors[];

extern unsigned char BODY_inno_Data[];
